[phases.setup]
nixPkgs = [
  "python313",
  "python313Packages.fastapi",
  "python313Packages.uvicorn",
  "python313Packages.python-multipart",
  "python313Packages.sqlalchemy",
  "python313Packages.alembic",
  "python313Packages.pydantic",
  "python313Packages.python-dotenv",
  "python313Packages.pytest",
  "python313Packages.pytest-asyncio",
  "python313Packages.httpx",
  "python313Packages.qrcode",
  "python313Packages.python-jose",
  "python313Packages.pillow",
  "python313Packages.python-socketio",
  "python313Packages.aiofiles",
  "python313Packages.slowapi",
  "python313Packages.redis",
  "python313Packages.psutil"
]

[phases.install]
cmds = [
  "echo 'Using Nix packages instead of pip'"
]

[phases.build]
cmds = [
  "mkdir -p ./data",
  "python -m alembic upgrade head"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"