[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel"
]

[phases.install]
cmds = [
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "mkdir -p ./data",
  "python -m alembic upgrade head"
]

[start]
cmd = "python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"