[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start_production.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.11"
# DATABASE_URL will be automatically set by Railway PostgreSQL service
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
DEBUG = "false"
QR_CODE_EXPIRY_HOURS = "24"
CACHE_TTL = "300"
MAX_CONCURRENT_REQUESTS = "100"