[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start_production.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.11"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
DEBUG = "false"
QR_CODE_EXPIRY_HOURS = "24"
CACHE_TTL = "300"
MAX_CONCURRENT_REQUESTS = "100"
ALLOWED_ORIGINS = "https://srcatttrackerbeta.vercel.app,https://srcatttrackerbeta-*.vercel.app,https://*.vercel.app"